I"¨	<ul>
  <li><strong>Origin</strong>:
    <ul>
      <li>The ValueError raised after typed <code class="highlighter-rouge">pip3 freeze &gt; requirements.txt&gt;</code> and it gave: <code class="highlighter-rouge">ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown version] (c:\users\james\appdata\local\programs\python\python37\lib\site-packages))</code></li>
      <li>The error like:</li>
    </ul>

    <p>```python
  Exception:
  Traceback (most recent call last):
    File ‚Äúc:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_vendor\pkg_resources__init__.py‚Äù, line 2584, in version
      return self._version
    File ‚Äúc:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_vendor\pkg_resources__init__.py‚Äù, line 2691, in <strong>getattr</strong>
      raise AttributeError(attr)
  AttributeError: _version</p>

    <p>During handling of the above exception, another exception occurred:</p>

    <p>Traceback (most recent call last):
    File ‚Äúc:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_internal\cli\base_command.py‚Äù, line 176, in main
      status = self.run(options, args)
    File ‚Äúc:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_internal\commands\list.py‚Äù, line 148, in run
      self.output_package_listing(packages, options)
    File ‚Äúc:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_internal\commands\list.py‚Äù, line 205, in output_package_listing
      data, header = format_for_columns(packages, options)
    File ‚Äúc:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_internal\commands\list.py‚Äù, line 271, in format_for_columns
      row = [proj.project_name, proj.version]
    File ‚Äúc:\users\james\appdata\local\programs\python\python37\lib\site-packages<br />
  pip_vendor\pkg_resources__init__.py‚Äù, line 2589, in version
      raise ValueError(tmpl % self.PKG_INFO, self)
  ValueError: (‚ÄúMissing ‚ÄòVersion:‚Äô header and/or METADATA file‚Äù, Unknown [unknown
  version] (c:\users\james\appdata\local\programs\python\python37\lib\site-package
  s))```
  <a href="https://stackoverflow.com/questions/54454367/different-error-messages-when-using-pip-install-pip-list-ect">link</a></p>
  </li>
  <li><strong>root cause</strong> is reffered to [here]((https://github.com/pypa/pip/pull/6225).</li>
</ul>
:ET